import ManualLayout from '@/components/ManualLayout'
import Callout from '@/components/manual/Callout'

export default function Page({ title }) {
  return (
    <ManualLayout title={title}>
      <p>La grana cochinilla es un colorante natural obtenido del insecto parásito Dactylopius coccus, una especie perteneciente al orden Hemiptera que vive exclusivamente sobre cactáceas del género Opuntia, comúnmente conocidos como nopales en México, tunas en Sudamérica y chumberas en España. La hembra, de cuerpo ovalado, permanece sobre las pencas inmóvil y cubierta por una sustancia cerosa blanquecina semejante al algodón. Su aspecto es tan extraño que, cuando llegó a Europa, muchos comerciantes y naturalistas creyeron que se trataba de una semilla, un fruto deshidratado o incluso una sustancia mineral, interpretación reforzada por el secretismo con el que la Corona española protegía su origen y sus métodos de producción.</p>
      <p>La grana cochinilla es probablemente el tinte natural con la historia cultural, política y económica más compleja del mundo. Comenzado porque uno de los colores principales que se pueden obtener es rojo escarlata, asociado a la sangre, el fuego, la pasión, el sacrificio, el poder y el peligro en diferentes culturas; un color que en el viejo mundo era difícil de obtener y de fijar. Antes de la conquista española, las fuentes de rojo más comunes eran óxidos de tierra que daban tonos apagados; plantas altas en alizarina como la Rubia tinctorum, que daba rojos con base anaranjada o coral; e insectos que, igual que la grana cochinilla, contienen ácido carmínico pero en cantidades mucho menores, como el quermes, del cual se obtienen tonos carmines pero que resultaba extremadamente caro, difícil de obtener y a veces inestable.</p>
      <p>La llegada de la grana cochinilla a Europa y Asia provocó una verdadera revolución, pues su color escarlata y carmesí era el colorante más intenso y estable que hubieran visto jamás. Llegó a ser más costosa que la plata, solo superada por el oro, manteniéndose en tendencia por más de 300 años en vestuarios cortesanos, en textiles áulicos y en uniformes como símbolo de prestigio, riqueza y estatus social. Fue además utilizado como pigmento en obras de arte, particularmente popular para crear glaseados, veladuras, gamas cálidas y para estabilizar los tonos en lienzos y tablas. Es rastreable en el arte virreinal mexicano, y también en obras de El Greco, Velázquez, Rembrandt, Zurbarán, Murillo, Goya, Tiziano, Tintoretto, Rubens, Van Dyck, Ter Borch y hasta Van Gogh.</p>
      <p>Su explotación en América provocó grandes estragos en las comunidades de los pueblos originarios. Era tan codiciada que los buques que llevaban cargamento de grana cochinilla eran interceptados y secuestrados por piratas, y se utilizaba como regalo diplomático e instrumento de negociación entre coronas. Algunas ciudades europeas prohibieron su utilización porque su popularidad afectaba la comercialización de los colorantes locales, y muchos reinos intentaron sabotear el monopolio español sin éxito durante siglos.</p>
      <p>El cultivo de la grana cochinilla, conocida en náhuatl como nocheztli, que literalmente significa “sangre de nopal”, fue desarrollado y perfeccionado en Mesoamérica desde tiempos prehispánicos. Se utilizó ampliamente como remedio medicinal y en todos los ámbitos que requerían color: cosméticos, textiles, usos ceremoniales, decoración de cerámica, escritura pictográfica y elaboración de códices, desde al menos el siglo II a. C. Su producción exige trabajo constante durante todo el año y consiste en plantar y cuidar nopaleras en climas semiáridos, inocularlas manualmente con hembras fecundadas que se adhieren a las pencas y se alimentan de la savia durante aproximadamente tres meses, para después recolectarlas justo antes de la oviposición, momento en que la concentración de ácido carmínico es mayor. Se calcula que hacen falta unos 70000 insectos secos para producir apenas un kilo de grana cochinilla. Una vez recolectadas, las hembras se secan, tradicionalmente al sol, en hornos o mediante calor controlado, hasta adquirir un aspecto arrugado y oscuro, formando la llamada “grana”, que luego se muele para extraer el color en agua caliente. Los tonos pueden modificarse, pues es sensible al pH. Además del famoso escarlata, se pueden obtener muchas variedades de anaranjados, rosas, lilas y morados. Los extractos resultantes pueden emplearse directamente como tinte soluble o transformarse</p>
      <p>en pigmento insoluble mediante la adición de alumbre, que precipita el ácido carmínico y genera la llamada laca de carmín.</p>
      <p>El verdadero declive de la grana cochinilla llegó en la segunda mitad del siglo XIX, cuando el modelo económico que la había sostenido empezó a perder sentido frente a la revolución industrial. El punto de quiebre fue en 1856, cuando el químico inglés William Henry Perkin sintetizó por accidente el primer colorante artificial de la historia, llamado mauveína. Inaugurando una nueva era de tintes sintéticos más baratos, uniformes y fáciles de producir en masa. A partir de entonces, la industria química europea desplazó progresivamente a los colorantes naturales y la cochinilla dejó de ser la reina del rojo en el mercado global. Sin embargo, nunca ha desaparecido del todo, diversas investigaciones recientes han confirmado su inocuidad como colorante alimentario. La cochinilla se mantiene vigente y controversial. Hoy sigue utilizándose como colorante alimentario (E 120) en jarabes, pasteles, helados, embutidos y licores, además de cosméticos y pigmentos de arte.</p>
    </ManualLayout>
  )
}
