import ManualLayout from '@/components/ManualLayout'
import Callout from '@/components/manual/Callout'

export default function Page({ title }) {
  return (
    <ManualLayout title={title}>
      <p>El índigo es uno de los tintes más antiguos del mundo. La evidencia de su uso se remonta al menos a miles de años en América, Mesopotamia, el antiguo Egipto y la India. Su estatus ha cambiado a lo largo de la historia: se ha utilizado para teñir desde lujosas telas de la realeza hasta mezclilla de trabajo.</p>
      <p>Los métodos y recetas más complicados dentro de los tintes naturales son los que contienen índigo. Hay muchas plantas alrededor del mundo de las que se puede extraer; las principales son del género Indigofera, incluyendo la más conocida, Indigofera tinctoria (añil o índigo verdadero), y también Indigofera suffruticosa (jiquilite). Otras plantas que también se utilizan para producir este colorante son Isatis tinctoria (glasto o pastel), Persicaria tinctoria (índigo japonés), Strobilanthes cusia (índigo de Assam) y Lonchocarpus cyanescens (índigo yoruba).</p>
      <p>La obtención del índigo natural es un proceso complejo, ya que ninguna planta contiene directamente el pigmento azul. La sustancia presente es un compuesto incoloro llamado indicano o indicán, un glucósido derivado de la glucosa.</p>
      <p>Una de las extracciones más populares se realiza fermentando la planta. En este proceso, enzimas y bacterias separan la glucosa y la transforman en otra molécula llamada indoxilo, una sustancia incolora y soluble en agua que abandona la planta y se suspende en el líquido fermentado. Después se agrega cal, que alcaliniza el medio, y se agita o se bate para incorporar oxígeno del aire. El oxígeno provoca que dos moléculas de indoxilo se unan, formando indigotina, que es insoluble en agua; el color cambia y se forma un lodo de pigmento de índigo que se asienta en el fondo. Finalmente, este sedimento se filtra, se seca en forma de piedras o pastillas y se muele lo más finamente posible hasta obtener polvo de pigmento de índigo, que puede almacenarse y utilizarse posteriormente para preparar un tinte.</p>
      <p>Para teñir con índigo, este debe diluirse en agua alcalina junto con un agente reductor como la fructosa. Este proceso elimina temporalmente el oxígeno de la molécula de índigo y la convierte en su forma reducida, llamada leucoíndigo, creando una solución amarillenta. La fibra se sumerge en esta solución y absorbe el color ámbar; después, al sacarla y entrar en contacto con el aire, el leucoíndigo se oxida nuevamente, recupera su forma azul insoluble y queda atrapado dentro de la fibra. A esta magia química le debemos uno de los azules más persistentes del mundo.</p>
      <p>En México existe una tradición milenaria alrededor del jiquilite (Indigofera suffruticosa), una planta que aún se cultiva y procesa en pequeñas comunidades de Oaxaca, Chiapas, Puebla y Guerrero, así como en otros países de la región, como El Salvador. El proceso de extracción se hace en piletas de fermentación y produce un pigmento de color profundo, ligeramente violáceo, distinto al índigo asiático.</p>
      <p>Te recomiendo trabajar con índigo natural de productores locales, y asegurarte de que no esté prerreducido (algunas presentaciones vienen ya activadas químicamente para teñir en frío, lo cual simplifica el proceso, pero te aleja del oficio y del control sobre el resultado. Además, suelen contener compuestos tóxicos como el hidrosulfito de sodio, que contamina el agua y daña a quien lo manipula). Suele costar más que el polvo industrial sintético, pero estás apoyando el trabajo de varias familias, el cuidado de una planta y la continuidad de un saber que se lleva transmitiendo por miles de años.</p>
      <p>A continuación, encontrarás dos fórmulas para preparar la tinta y teñir con ella, una guía para solucionar problemas y una receta de pasta de resistencia especial para índigo.</p>
    </ManualLayout>
  )
}
