---
el-origen-del-color:
- 8
- 8
el-origen-del-color/introduccion:
- 9
- 9
el-origen-del-color/el-color-en-la-naturaleza:
- 10
- 11
el-origen-del-color/principios-del-tenido-y-extraccion-de-tintes-naturales:
- 12
- 12
el-origen-del-color/materiales-y-herramientas:
- 13
- 13
el-origen-del-color/herramientas-basicas:
- 14
- 14
el-origen-del-color/herramientas-basicas/materiales-para-tenir:
- 14
- 14
el-origen-del-color/herramientas-basicas/materiales-para-tenir-con-indigo:
- 15
- 15
el-origen-del-color/herramientas-basicas/materiales-para-extraer-pigmentos:
- 16
- 16
el-origen-del-color/herramientas-basicas/materiales-para-preparar-pintura-y-aglutinantes:
- 16
- 16
el-origen-del-color/medidas-de-seguridad:
- 17
- 18
el-origen-del-color/preparacion-de-carbonatos:
- 19
- 19
el-origen-del-color/preparacion-de-carbonatos/receta-para-preparar-carbonato-de-calcio:
- 19
- 19
el-origen-del-color/preparacion-de-carbonatos/receta-para-preparar-carbonato-de-sodio:
- 20
- 21
color-sobre-fibra:
- 22
- 22
color-sobre-fibra/elegir-el-textil:
- 23
- 24
color-sobre-fibra/guia-de-lavado:
- 25
- 25
color-sobre-fibra/guia-de-lavado/lavado-simple:
- 25
- 25
color-sobre-fibra/guia-de-lavado/descrudado:
- 25
- 27
color-sobre-fibra/guia-de-mordentado:
- 28
- 28
color-sobre-fibra/guia-de-mordentado/mordientes:
- 28
- 30
color-sobre-fibra/guia-de-mordentado/receta-para-mordentar:
- 31
- 34
color-sobre-fibra/guia-de-tenido:
- 35
- 36
color-sobre-fibra/consejos-para-tenir-ropa:
- 37
- 37
color-sobre-fibra/modificadores-y-tratamientos-de-color:
- 38
- 38
color-sobre-fibra/modificadores-y-tratamientos-de-color/acido-tanico:
- 38
- 39
color-sobre-fibra/modificadores-y-tratamientos-de-color/acido-tanico/receta-de-pretratamiento-con-taninos:
- 40
- 40
color-sobre-fibra/modificadores-y-tratamientos-de-color/sulfato-ferroso:
- 41
- 41
color-sobre-fibra/modificadores-y-tratamientos-de-color/sulfato-ferroso/receta-de-bano-modificador-con-sulfato-ferroso:
- 41
- 41
color-sobre-fibra/modificadores-y-tratamientos-de-color/dibujos-con-sulfato-ferroso:
- 42
- 42
color-sobre-fibra/modificadores-y-tratamientos-de-color/acido-citrico:
- 43
- 43
? color-sobre-fibra/modificadores-y-tratamientos-de-color/acido-citrico/receta-para-moditicar-el-color-de-un-tinte-con-acido-citrico
: - 43
  - 43
color-sobre-fibra/modificadores-y-tratamientos-de-color/acido-citrico/dibujos-con-acido-citrico:
- 44
- 44
color-sobre-fibra/modificadores-y-tratamientos-de-color/acido-citrico/reservas-en-negativo-con-acido-citrico:
- 45
- 45
color-sobre-fibra/modificadores-y-tratamientos-de-color/carbonato-de-calcio:
- 46
- 46
? color-sobre-fibra/modificadores-y-tratamientos-de-color/carbonato-de-calcio/receta-para-modificar-el-color-de-un-tinte-con-carbonato-de-calcio
: - 46
  - 46
? color-sobre-fibra/modificadores-y-tratamientos-de-color/carbonato-de-calcio/receta-de-bano-intensificador-con-carbonato-de-calcio
: - 46
  - 46
color-sobre-fibra/modificadores-y-tratamientos-de-color/leche-de-soya:
- 47
- 47
color-sobre-fibra/modificadores-y-tratamientos-de-color/leche-de-soya/receta-de-leche-de-soya-casera:
- 47
- 47
color-sobre-fibra/modificadores-y-tratamientos-de-color/leche-de-soya/receta-para-pretratamiento-con-leche-de-soya:
- 48
- 48
color-sobre-fibra/tenir-con-plantas:
- 49
- 49
color-sobre-fibra/tenir-con-plantas/recomendaciones-antes-de-tenir:
- 49
- 49
color-sobre-fibra/tenir-con-plantas/receta-general-para-tenir-con-plantas:
- 50
- 50
color-sobre-fibra/tenir-con-plantas/receta-para-tenir-con-cascara-de-granada:
- 51
- 52
color-sobre-fibra/tenir-con-plantas/receta-para-tenir-con-palo-de-campeche:
- 53
- 54
color-sobre-fibra/tenir-con-plantas/receta-para-tenir-con-rubia:
- 55
- 57
color-sobre-fibra/tenir-con-grana-cochinilla:
- 58
- 59
color-sobre-fibra/tenir-con-grana-cochinilla/guia-basica-para-tenir-con-grana-cochinilla:
- 60
- 61
color-sobre-fibra/tenir-con-indigo:
- 62
- 62
color-sobre-fibra/tenir-con-indigo/receta-de-tinte-de-indigo-con-fructosa:
- 63
- 65
color-sobre-fibra/tenir-con-indigo/receta-de-tinte-de-indigo-con-sulfato-ferroso:
- 66
- 68
color-sobre-fibra/tenir-con-indigo/resolucion-de-problemas-al-tenir-con-indigo:
- 69
- 69
color-sobre-fibra/tenir-con-indigo/pasta-de-resistencia-para-indigo:
- 70
- 70
color-sobre-fibra/retenido:
- 71
- 72
color-sobre-fibra/impresion-botanica:
- 73
- 76
color-sobre-fibra/hapa-zome:
- 77
- 77
color-sobre-fibra/tinta-textil:
- 78
- 80
color-sobre-fibra/guia-de-cuidados:
- 81
- 82
pigmento-y-polvo:
- 83
- 83
pigmento-y-polvo/pigmentos-de-laca:
- 84
- 84
pigmento-y-polvo/azul-maya:
- 84
- 91
pigmento-y-polvo/cernir-pigmentos-minerales:
- 92
- 93
color-en-movimiento:
- 94
- 94
color-en-movimiento/recomendaciones-generales:
- 95
- 95
color-en-movimiento/tempera:
- 95
- 96
color-en-movimiento/tempera-grasa:
- 97
- 97
color-en-movimiento/pintura-textil:
- 98
- 99
color-en-movimiento/aglutinante-para-pastillas-de-acuarela:
- 100
- 100
color-en-movimiento/gouache:
- 101
- 101
color-en-movimiento/pasteles:
- 101
- 101
color-en-movimiento/pasteles/receta-para-pastel-suave:
- 102
- 102
color-en-movimiento/pasteles/receta-para-pastel-al-oleo:
- 103
- 103
color-cotidiano:
- 110
- 111
color-cotidiano/crayones:
- 103
- 104
color-cotidiano/gises:
- 105
- 105
color-cotidiano/tinta-botanica:
- 105
- 106
color-cotidiano/tinta-ferrogalica:
- 107
- 107
color-cotidiano/tinta-a-base-de-alcohol:
- 108
- 110
color-cotidiano/papel-artesanal-coloreado:
- 111
- 111
color-cotidiano/antotipia-con-curcuma:
- 112
- 112
color-cotidiano/velas:
- 112
- 114
color-cotidiano/envoltorios-de-cera-de-abeja:
- 115
- 117
color-cotidiano/masa-moldeable:
- 118
- 118
color-cotidiano/huevos-de-pascua:
- 119
- 120
atlas-del-color:
- 121
- 130
epilogo:
- 131
- 131
glosario:
- 132
- 136
