import ManualLayout from '@/components/ManualLayout'
import Callout from '@/components/manual/Callout'

export default function Page({ title }) {
  return (
    <ManualLayout title={title}>
      <p><strong>Ácido</strong> Sustancia con un pH menor a 7. En los procesos de tintura, los ácidos pueden modificar el color de algunos tintes.</p>
      <p><strong>Afinidad</strong> Capacidad que tiene un colorante para adherirse o fijarse a una fibra o material determinado. Algunas fibras tienen mayor afinidad por ciertos tintes que otras.</p>
      <p><strong>Aglutinante</strong> Sustancia que permite que un pigmento en polvo se adhiera a un soporte. Es el componente que une las partículas de color y forma la película de pintura. Ejemplos comunes son la goma arábiga y el huevo.</p>
      <p><strong>Alcaloides</strong> Compuestos nitrogenados producidos por plantas principalmente como defensa química. Aunque no todos son pigmentos, algunos alcaloides poseen color o participan en procesos tintóreos.</p>
      <p><strong>Antocianinas</strong> Pigmentos vegetales solubles en agua, responsables de los colores azules, morados y rojos en muchas plantas. Son altamente sensibles al pH: cambian de color en presencia de ácidos y bases. Se encuentran en la col morada, la flor de Jamaica, los frutos rojos y muchas flores.</p>
      <p><strong>Apresto</strong> Recubrimiento que se aplica a los tejidos durante su producción industrial para mejorar su apariencia, textura o resistencia. Puede estar hecho de almidón, resinas sintéticas u otras sustancias químicas. Para el teñido natural, el apresto debe retirarse antes de comenzar, ya que forma una barrera entre la fibra y el colorante que impide una absorción uniforme del tinte. El proceso para eliminarlo se llama descrudado.</p>
      <p><strong>Arcilla palygorskita</strong> Mineral arcilloso perteneciente al grupo de los filosilicatos de magnesio y aluminio, también conocido como atapulgita. Se encuentra de forma natural en ciertos suelos arcillosos, especialmente abundantes en el sureste de Estados Unidos, y se considera un tipo de tierra de batán. También existen depósitos más pequeños en México, donde tuvo gran importancia histórica: se cree que fue uno de los componentes utilizados en la elaboración del azul maya durante la época precolombina.</p>
      <p><strong>Base (alcalino)</strong> Sustancia con un pH mayor a 7. En los procesos de tintura, las bases pueden modificar el color de algunos tintes y se utilizan para reducir el índigo.</p>
      <p><strong>Betalaínas</strong> Pigmentos hidrosolubles presentes principalmente en plantas del orden Caryophyllales, como la betabel o la bugambilia. Se dividen en betacianinas (rojos y magentas) y betaxantinas (amarillos y naranjas). Son colores muy vivos pero generalmente sensibles al calor, la luz y los cambios de pH, por lo que no tienen estabilidad en el textil.</p>
      <p><strong>Carotenoides</strong> Pigmentos liposolubles responsables de muchos amarillos, naranjas y rojos intensos en flores, frutos y raíces. Son comunes en plantas como el achiote, la caléndula o la zanahoria. Muchos carotenoides tienen baja afinación por fibras y pueden degradarse con facilidad por exposición a la luz y al oxígeno.</p>
      <p><strong>Cernir</strong> Proceso de separar y refinar partículas sólidas según su tamaño mediante el uso de una malla, tamiz o cedazo. En la preparación de pigmentos, cernir permite eliminar fragmentos gruesos, impurezas o partículas mal molidas, obteniendo un polvo más fino, homogéneo y adecuado para dispersarse de manera uniforme en un medio pictórico.</p>
      <p><strong>Colorante</strong> Sustancia soluble que transmite color al disolverse en un líquido, generalmente agua. Los colorantes se adhieren directamente a las fibras o requieren mordientes para fijarse.</p>
      <p><strong>Curcuminoides</strong> Familia de compuestos fenólicos responsables del color amarillo intenso de la cúrcuma. El principal es la curcumina. Son pigmentos muy brillantes y sensibles al pH, capaces de virar hacia tonos anaranjados o rojizos en medios alcalinos. Aunque producen colores luminosos, suelen tener baja resistencia a la luz.</p>
      <p><strong>Descrudar</strong> Proceso de lavado profundo de una fibra textil para eliminar grasas, ceras, residuos de fabricación y otras sustancias que pueden interferir con la fijación del tinte. Se realiza con agua caliente y un álcali suave como el carbonato de sodio y jabón neutro.</p>
      <p><strong>Encáustica</strong> Técnica de pintura antigua que combina pigmentos con cera derretida, generalmente cera de abeja, aplicada en caliente sobre un soporte. Es uno de los métodos pictóricos más antiguos documentados. Es la antecesora directa de los crayones modernos.</p>
      <p><strong>Fijación</strong> Proceso por el cual un colorante o pigmento queda adherido de manera permanente o duradera a una fibra o superficie. La fijación puede lograrse mediante mordientes, calor, oxidación o tiempo de curado, dependiendo del tinte y el material.</p>
      <p><strong>Flavonoides</strong> Gran grupo de pigmentos vegetales solubles en agua responsables de muchos tonos amarillos, cremas, marfiles y algunos rojos o azules suaves en flores, hojas y cortezas. Son muy comunes en plantas tintóreas y suelen reaccionar fuertemente al pH y a los mordientes, cambiando de color según el medio. Incluyen subgrupos como flavonas, flavonoles y antocianinas.</p>
      <p><strong>Fructosa</strong> Azúcar natural presente en frutas y miel. En la tintura con índigo puede emplearse como agente reductor para crear un baño de reducción más suave y sin agentes tóxicos.</p>
      <p><strong>Homoisoflavonoides</strong> Grupo de compuestos vegetales relacionado estructuralmente con los flavonoides. Algunos presentan propiedades colorantes y antioxidantes, especialmente en tonos rojizos, púrpuras o marrones.</p>
      <p><strong>Indigoides</strong> Familia de moléculas orgánicas pigmentadas caracterizadas por una estructura química basada en el núcleo del índigo. Son compuestos conjugados capaces de absorber luz en el espectro visible, produciendo principalmente tonos azules y púrpuras. Los indigoides incluyen moléculas como índigo e indirubina, presentes en distintas plantas y algunos organismos animales. Se distinguen de muchos otros pigmentos vegetales porque son insolubles en agua en su forma oxidada y deben reducirse químicamente para poder adherirse a las fibras textiles.</p>
      <p><strong>Inocular</strong> Introducir un organismo vivo en un medio adecuado para que se desarrolle. En la cría de grana cochinilla, se inoculan los nopales con hembras del insecto para que se establezcan, se reproduzcan y formen una nueva colonia.</p>
      <p><strong>Levigación</strong> Proceso para separar partículas finas de un material sólido mediante agua. Se mezcla el material con agua, se agita y se deja reposar unos segundos para que las partículas pesadas caigan al fondo; el agua turbia con las partículas finas en suspensión se decanta a otro recipiente, donde el pigmento se asienta lentamente. Es una técnica antigua para preparar pigmentos minerales a partir de tierras.</p>
      <p><strong>Medio</strong> Mezcla que contiene el aglutinante y, en ocasiones, otros aditivos que modifican la textura, fluidez o brillo de una pintura.</p>
      <p><strong>Mordentado</strong> Proceso previo a la tintura en el que la fibra se trata con un mordiente para mejorar la fijación del colorante y aumentar la solidez del color.</p>
      <p><strong>Mordiente</strong> Sustancia que ayuda a fijar un colorante a una fibra formando un puente químico entre ambos. Algunos mordientes tradicionales comunes incluyen el alumbre, el hierro y el cobre.</p>
      <p><strong>Neutralización</strong> Proceso químico en el que un ácido y una base reaccionan para equilibrar el pH de una solución.</p>
      <p><strong>Oxidación</strong> Reacción química en la que una sustancia pierde electrones al entrar en contacto con oxígeno u otros agentes oxidantes. En teñido natural, este proceso puede transformar o fijar ciertos colores, como ocurre con el índigo al exponerse al aire.</p>
      <p><strong>pH</strong> Escala que mide la acidez o alcalinidad de una solución, generalmente de 0 a 14. El pH influye en el comportamiento de muchos tintes naturales y puede cambiar el color final.</p>
      <p><strong>Pigmento</strong> Sustancia colorante insoluble en agua que se presenta en forma de polvo. A diferencia de los colorantes, los pigmentos requieren un aglutinante para adherirse a una superficie.</p>
      <p><strong>Precipitado</strong> Sólido que se forma cuando una sustancia disuelta en un líquido se vuelve insoluble y se separa de la solución. En tintes naturales, este proceso se utiliza para obtener pigmentos a partir de colorantes.</p>
      <p><strong>Precursor</strong> Sustancia que participa en una reacción química y se transforma en otro compuesto. En algunos tintes naturales, el color visible aparece solo después de que el precursor se transforma mediante oxidación, fermentación u otros procesos.</p>
      <p><strong>Reducción</strong> Reacción química en la que una sustancia gana electrones; es la reacción opuesta a la oxidación. En tintura con índigo, la reducción transforma el pigmento insoluble en una forma soluble que puede penetrar las fibras.</p>
      <p><strong>Quinonas</strong> Familia de compuestos orgánicos con estructuras aromáticas oxidadas que producen colores intensos y generalmente resistentes. En teñido natural suelen generar tonos amarillos, anaranjados, rojos, marrones y negros dependiendo de la planta y del mordiente utilizado. Muchas quinonas tienen buena afinación por fibras textiles y alta solidez a la luz.</p>
      <p><strong>Solidez</strong> Capacidad de un color para resistir el paso del tiempo, los lavados, la luz solar y otros factores externos sin perder intensidad. Un buen mordentado y una correcta fijación aumentan la solidez del color.</p>
      <p><strong>Soporte</strong> Superficie o material sobre el cual se aplica un pigmento o pintura. Puede ser papel, tela, madera , muro u otros materiales.</p>
      <p><strong>Tanino</strong> Compuesto vegetal de color amarillo parduzco y sabor astringente, presente en cortezas, hojas, frutos y agallas de muchos árboles y plantas. Los taninos pueden actuar como mordientes naturales y, al combinarse con sales de hierro, forman compuestos oscuros utilizados en tintes y tintas como la ferrogálica.</p>
      <p><strong>Tinta</strong> Líquido coloreado, con o sin aglutinante, que se utiliza para escribir, dibujar o pintar sobre papel u otras superficies. A diferencia del tinte, la tinta no penetra ni se fija químicamente en la fibra; permanece en la superficie.</p>
      <p><strong>Tinte</strong> Sustancia que penetra en una fibra y se fija a ella, produciendo un cambio de color permanente o de larga duración. En este manual, “tinte” se usa para referirse al colorante en forma líquida (después de la extracción) y al producto final de un baño de teñido.</p>
    </ManualLayout>
  )
}
