import { Link } from '@inertiajs/react'
import ManualLayout from '@/components/ManualLayout'

export default function Page({ title }) {
  return (
    <ManualLayout title={title}>
      <p>Antes de poner cualquier planta en una olla, me parece importante entender de dónde viene su color. Las plantas no hacen color por accidente ni para nosotros. Lo hacen para sobrevivir. Los pigmentos que producen tienen funciones muy concretas: atraer polinizadores, protegerse del sol, avisar que un fruto ya está listo, defenderse de hongos o insectos.</p>
      <p>Esos colores son moléculas. Compuestos que la planta fabrica como parte de su metabolismo, y fabricarlos tiene un costo: la planta invierte mucha energía para construir estas estructuras moleculares. No es un proceso menor ni accidental. Es una decisión biológica.</p>
      <p>Para entender por qué una molécula tiene color hay que pensar en el sol. Su luz contiene todos los colores del espectro. Cuando toca una planta, parte de ella es absorbida y parte es reflejada, la que absorbió puede convertirse en energía para la planta, y lo que reflejó es lo que llega a nuestros ojos. Lo que vemos es, literalmente, lo que la planta no utilizó. El azul profundo del añil refleja azul porque absorbe casi todo lo demás. Lo verde de la clorofila refleja verde porque absorbe luz roja y azul para usarla como combustible.</p>
      <p>La mayoría de los pigmentos que podemos extraer pertenecen a un grupo llamado metabolitos secundarios. La planta no los necesita para crecer y respirar, pero sí para relacionarse con su entorno. Son su lenguaje con el mundo exterior. Y nosotros podemos aprovecharlo y capturarlo. No me parece una casualidad que en culturas prehispánicas se creyera que pintaban con el corazón de las plantas, porque en cierta forma, así es.</p>
      <p>Dentro de ese grupo hay familias muy distintas, y no todos los pigmentos que existen en una planta se pueden utilizar. Algunos se destruyen con el calor, otros nunca pasan al agua, y la mayoría simplemente no quieren quedarse: las antocianinas, que dan los morados y rosas de la flor de Jamaica, la flor de jacaranda o la col morada, cambian de tono según el pH del medio, son fascinantes pero poco confiables. Las betalaínas dan el rojo del betabel y la pitaya, son brillantes e intensas, pero muy sensibles al calor. La clorofila, responsable del verde de casi todo lo que vemos, es técnicamente un pigmento, pero es tan inestable que raramente sirve para teñir, pues se degrada rápido con el calor y la luz.</p>
      <p>Los que sí nos interesan son los que, bajo ciertas condiciones, pueden formar un vínculo con el material que queremos colorear. Los flavonoides son quizás los más abundantes: están en flores, hojas y frutos de miles de plantas y dan amarillos, naranjas y verdes cálidos, están en el cempasúchil, la cebolla, el palo amarillo. Los taninos viven en cortezas, semillas y madera: el nogal, el encino, la granada, el zumaque, tiñen beige y marrón, al oxidarse producen negros y grises, y esa afinidad los hace perfectos como base para otros colores. Las quinonas incluyen algunos de los tintes más sólidos de la historia: cártamo, ruibarbo, raíz de rubia, henna, son estables, confiables, con una paleta que va del amarillo al rojo y el morado. Y luego están los indigoides, como el añil, que son un mundo aparte: no se disuelven en agua, no se extraen hirviendo, y su proceso requiere crear un ambiente sin oxígeno para que puedan adherirse a la fibra y oxidarse al contacto con el aire, de ahí ese momento en que la tela emerge amarilla y se vuelve azul.</p>
      <p>Pero no todo el color con el que podemos trabajar viene de las plantas. Las rocas sedimentarias como la sienna o la hematita deben su color a los óxidos de hierro que las componen: minerales formados durante millones de años por la acumulación de sedimentos y la acción del agua y el oxígeno. No son pigmentos biológicos, no tienen metabolismo ni función de comunicación, pero producen algunos de los ocres, rojos y tierras más bellos y confiables que existen. Fueron los primeros pigmentos que usó el ser humano para pintar, y siguen siendo insustituibles. Algunos insectos, como la grana cochinilla también producen pigmentos, en su caso como mecanismo de defensa, y el ácido carmínico que secreta es uno de los colorantes más sólidos y brillantes que se conocen. Aunque en este manual trabajamos principalmente con plantas, haremos una pausa para hablar de tierras y <Link href="/manual-del-color-vivo/color-sobre-fibra/tenir-con-grana-cochinilla" className="underline text-orange-ink hover:text-orange">grana cochinilla</Link> más adelante.</p>
      <p>Sé que todos estos nombres pueden sonar complicados, pero no necesitas aprenderlos ni saber mucha química para teñir o pintar con la naturaleza. Nadie la sabía durante miles de años y teñían con ella perfectamente. Lo que sí cambia cuando entiendes aunque sea un poco lo que pasa dentro de esa olla es la libertad: puedes improvisar, resolver lo que sale mal, adaptar las recetas a lo que tienes a la mano. Y eso, en mi experiencia, es cuando el proceso deja de ser sobre seguir instrucciones y se convierte en algo tuyo.</p>
      <p>Al final de este manual encontrarás la sección <Link href="/manual-del-color-vivo/atlas-del-color" className="underline text-orange-ink hover:text-orange">Atlas del color</Link>: un mapa ilustrado de las plantas con las que puedes empezar. Las que producen los tintes más estables, las que han acompañado a tejedores y tintoreros durante siglos, y que siguen aquí, hablándonos.</p>
    </ManualLayout>
  )
}
