import ManualLayout from '@/components/ManualLayout'

export default function Page({ title }) {
  return (
    <ManualLayout title={title}>
      <p>Los colores vivos me atraparon en el verano del 2012, estudiaba moda y estaba conflictuada entre mi amor por los colores y las telas y lo terrible de su industria. Pasé por una etapa oscura: no quería comprar nada, sentía culpa, nada de lo que podía crear se sentía suficiente, como si el mundo ya tuviera demasiado y mis manos no tuvieran derecho a añadir más.</p>
      <p>Un día, en medio de un caos interno, aprendí que los tintes sintéticos para teñir ropa eran bastante recientes. En 1856, un jovencito de 18 años llamado William Perkin intentaba obtener una medicina para la malaria y accidentalmente creó un tinte sintético color morado a base de alquitrán con el que se podían teñir textiles. Pasaron décadas para que ese color y muchos más estuvieran disponibles comercialmente; antes de eso, toda la ropa era teñida con plantas, barro, insectos e incluso moluscos. Me di cuenta que seguimos en medio de una revolución. La cantidad de colores disponibles nunca había sido tan grande; hoy en día, las personas pueden llevar puesto cualquier color. Es tan emocionante y divertido que creo que todavía no nos hemos cuestionado lo suficiente si es la mejor idea para nuestra piel, el agua o la naturaleza.</p>
      <p>A principios del 2000, muchas marcas seguían utilizando índigo natural para darle su color característico a los jeans, así que decidí usar ese tinte para aprender a teñir. El índigo, hablando científicamente, todavía contiene muchos misterios, además de que no se me puede ocurrir cómo es que un procedimiento que incluye tantos pasos fue descubierto paralelamente por tantas culturas alrededor del mundo. Ver cómo un trocito de tela cambiaba de amarillo a azul intenso al contacto con el aire cambió mi vida: 6000 años de historia contenidos en una olla con agua, plantas, azúcar y cal. Desde entonces siento que los colores de las plantas me persiguen.</p>
      <p>Tiño y pinto con plantas porque no puedo dejar de hacerlo, me vuelco en la práctica cada vez que puedo. El proceso de recolección y extracción me resulta sumamente gratificante, he encontrado calma, conexión con la naturaleza y un escondite para la observación, la intuición y el espacio interior. Llevar plantas puestas hace que me sienta distinta. Con el tiempo, sentí la necesidad de vestir fibras naturales y las prendas teñidas con plantas se volvieron mis favoritas para ocasiones particulares como hacer ejercicio, meditar o descansar. Utilizar esos mismos colores para hacer acuarelas, crayones o pintura resultó ser otra puerta apasionante y asombrosa.</p>
      <p>Este manual es una compilación de todo lo que he experimentado y aprendido a lo largo de más de una década: es sobre el regalo de sentir lo que siento cuando extraigo el color de la naturaleza y poder compartirlo con otros. Hay fórmulas muy simples, y algunas que pueden resultar frustrantes. Mi único consejo es que recuerdes que todo lo que proviene de la tierra presentará una transformación; los colores de origen natural se mueven con la luz, se oxidan, tienen memoria y voluntad, el proceso no promete control, pero serán tu mejor compañía.</p>
    </ManualLayout>
  )
}
