import ManualLayout from '@/components/ManualLayout'

export default function Page({ title }) {
  return (
    <ManualLayout title={title}>
      <p>Extraer tintes y colorantes naturales es relativamente simple. La mayoría de los colores de origen orgánico se extraen en agua hirviendo por una hora a fuego medio-bajo, después se puede introducir un material natural para colorearlo o precipitar el tinte para obtener un pigmento en polvo, que después puede mezclarse con un aglutinante y utilizarse para pintar. Las posibilidades son infinitas.</p>
      <p>Antes de continuar, vale la pena aclarar algo que suele generar confusión: pigmento, colorante y tinte no son lo mismo, y a veces se usan indistintamente. Aunque por definición un pigmento es un compuesto químico que da color a una sustancia u organismo, en arte se suele hacer una distinción: los pigmentos son partículas sólidas que no se disuelven, sino que flotan en un medio (agua, aceite, goma) y colorean por contacto y adhesión, no por absorción; mientras que los colorantes son partículas coloreadas que sí son solubles o se disuelven en alguna etapa de su uso. El tinte es ese colorante disuelto en agua, listo para transferirse a una fibra o superficie. La diferencia práctica es enorme: un textil teñido absorbe el color en sus fibras; un textil pintado con pigmento lo lleva encima. Por eso, el teñido generalmente necesita fijadores (llamados mordientes) que abren la fibra y fijan el colorante desde adentro, mientras que los pigmentos requieren aglutinantes que los adhieran por fuera. En este manual vas a encontrar los tres mundos: extraer el tinte para teñir, precipitarlo para hacer pigmento, y mezclarlo para pintar.</p>
      <p>Por otro lado, los colorantes naturales tienen un lado complejo que, aunque pueda intimidar, es necesario entender para dominar la teoría detrás de sus procesos: el uso de mordientes, modificadores de color, enlaces y la estructura molecular de los materiales tintóreos. En los siguientes capítulos te explicaré la ciencia detrás de cada proceso de una manera sencilla, pero quiero aclarar que estos no son exhaustivos. No comprenden todo lo que se puede hacer o se ha hecho con tintes naturales, especialmente hablando de modificadores de color y métodos de fijación con otros materiales que no sean sales metálicas a base de aluminio. Existen muchas fórmulas históricas fascinantes que van más allá de lo que cubre este manual. Mi elección ha sido trabajar siempre con las sales metálicas más seguras, de grado cosmético o alimenticio, y con procesos que reduzcan el gasto de agua, energía y recursos. No por limitación, sino por convicción.</p>
    </ManualLayout>
  )
}
